apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: fluent-bit
    meta.helm.sh/release-namespace: logging
  creationTimestamp: "2025-11-05T15:22:08Z"
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 4.1.0
    helm.sh/chart: fluent-bit-0.54.0
  name: fluent-bit
  namespace: logging
  resourceVersion: "848998"
  uid: 856fb418-cff9-4aca-99d4-cec749c9ebc0
spec:
  clusterIP: 10.96.79.182
  clusterIPs:
  - 10.96.79.182
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 2020
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/name: fluent-bit
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
